Rails.application.config.assets.precompile += %w( icon/top-tray.png )
Rails.application.config.assets.precompile += %w( sidebar-menu-arrow.png )
Rails.application.config.assets.precompile += %w( pullup.png )
Rails.application.config.assets.precompile += %w( icon/portlet-tray.png )
Rails.application.config.assets.precompile += %w( icon/status.png )
Rails.application.config.assets.precompile += %w( logo.png )