# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b563fb89352174dc59def01ed6550d912e7d04f99a808d9130d78633f298e4efe28e3af62be7742572eb4849ef1b02163daf6fe90f354b0de24ddbce0a324dd

test:
  secret_key_base: 7487dd5e2844480deef0e72741c851a38c9046cda55a20e110f35e1d106005d73a57d65487deca18e1e2757f789b220537e8076889c5ada34fa5fa4ba69fea10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
