require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvanceBookingsController do

  # This should return the minimal set of attributes required to create a valid
  # AdvanceBooking. As you add validations to AdvanceBooking, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvanceBookingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all advance_bookings as @advance_bookings" do
      advance_booking = AdvanceBooking.create! valid_attributes
      get :index, {}, valid_session
      assigns(:advance_bookings).should eq([advance_booking])
    end
  end

  describe "GET show" do
    it "assigns the requested advance_booking as @advance_booking" do
      advance_booking = AdvanceBooking.create! valid_attributes
      get :show, {:id => advance_booking.to_param}, valid_session
      assigns(:advance_booking).should eq(advance_booking)
    end
  end

  describe "GET new" do
    it "assigns a new advance_booking as @advance_booking" do
      get :new, {}, valid_session
      assigns(:advance_booking).should be_a_new(AdvanceBooking)
    end
  end

  describe "GET edit" do
    it "assigns the requested advance_booking as @advance_booking" do
      advance_booking = AdvanceBooking.create! valid_attributes
      get :edit, {:id => advance_booking.to_param}, valid_session
      assigns(:advance_booking).should eq(advance_booking)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdvanceBooking" do
        expect {
          post :create, {:advance_booking => valid_attributes}, valid_session
        }.to change(AdvanceBooking, :count).by(1)
      end

      it "assigns a newly created advance_booking as @advance_booking" do
        post :create, {:advance_booking => valid_attributes}, valid_session
        assigns(:advance_booking).should be_a(AdvanceBooking)
        assigns(:advance_booking).should be_persisted
      end

      it "redirects to the created advance_booking" do
        post :create, {:advance_booking => valid_attributes}, valid_session
        response.should redirect_to(AdvanceBooking.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advance_booking as @advance_booking" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvanceBooking.any_instance.stub(:save).and_return(false)
        post :create, {:advance_booking => { "name" => "invalid value" }}, valid_session
        assigns(:advance_booking).should be_a_new(AdvanceBooking)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvanceBooking.any_instance.stub(:save).and_return(false)
        post :create, {:advance_booking => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advance_booking" do
        advance_booking = AdvanceBooking.create! valid_attributes
        # Assuming there are no other advance_bookings in the database, this
        # specifies that the AdvanceBooking created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdvanceBooking.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => advance_booking.to_param, :advance_booking => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested advance_booking as @advance_booking" do
        advance_booking = AdvanceBooking.create! valid_attributes
        put :update, {:id => advance_booking.to_param, :advance_booking => valid_attributes}, valid_session
        assigns(:advance_booking).should eq(advance_booking)
      end

      it "redirects to the advance_booking" do
        advance_booking = AdvanceBooking.create! valid_attributes
        put :update, {:id => advance_booking.to_param, :advance_booking => valid_attributes}, valid_session
        response.should redirect_to(advance_booking)
      end
    end

    describe "with invalid params" do
      it "assigns the advance_booking as @advance_booking" do
        advance_booking = AdvanceBooking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvanceBooking.any_instance.stub(:save).and_return(false)
        put :update, {:id => advance_booking.to_param, :advance_booking => { "name" => "invalid value" }}, valid_session
        assigns(:advance_booking).should eq(advance_booking)
      end

      it "re-renders the 'edit' template" do
        advance_booking = AdvanceBooking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvanceBooking.any_instance.stub(:save).and_return(false)
        put :update, {:id => advance_booking.to_param, :advance_booking => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advance_booking" do
      advance_booking = AdvanceBooking.create! valid_attributes
      expect {
        delete :destroy, {:id => advance_booking.to_param}, valid_session
      }.to change(AdvanceBooking, :count).by(-1)
    end

    it "redirects to the advance_bookings list" do
      advance_booking = AdvanceBooking.create! valid_attributes
      delete :destroy, {:id => advance_booking.to_param}, valid_session
      response.should redirect_to(advance_bookings_url)
    end
  end

end
